# -*- coding: utf-8 -*-
"""TUGASPRAKTIKUM_6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H5H3XATpeK9IRgcFRxIBfHlLu6LOoGtK

SOAL 1
"""

def tambah_barang(inventory):
    try:
      kode_barang = input("Masukkan kode barang: ")
    except ValueError:
      print("eror karna bilangan negatif dan huruf,harus bilangan bulat")
      return
    nama_barang = input("Masukkan nama barang: ")
    try:
      jumlah = int(input("Masukkan jumlah: "))
      if jumlah < 1:
        print("error karena bilangan negatif")
        return
      harga = int(input("Masukkan harga: "))
      if harga <1:
        print("error karna bilangan negatif")
        return

    except ValueError:
      print("eror karna bilangan negatif dan huruf,harus bilangan bulat")
      return

    inventory[kode_barang] = {"kode": kode_barang, "nama": nama_barang, "jumlah": jumlah, "harga": harga}
    print("Barang berhasil ditambahkan!")


def hapus_barang(inventory):
    while True:
        hapus = input("Cari menggunakan kode barang (1) atau menggunakan nama barang (2): ")
        if hapus == "1":
            hapus_kode_barang = input("Masukkan kode barang yang ingin dihapus: ")
            if hapus_kode_barang in inventory:
                del inventory[hapus_kode_barang]
                print("Barang berhasil dihapus!")
            else:
                print("Barang tidak ditemukan!")
            break
        elif hapus == "2":
            hapus_nama_barang = input("Masukkan nama barang yang ingin dihapus: ").lower()
            barang_dihapus = []
            for barang, data in inventory.items():
                if data['nama'].lower() == hapus_nama_barang:
                    barang_dihapus.append(barang)
            for barang in barang_dihapus:
                del inventory[barang]
            if barang_dihapus:
                print("Barang berhasil dihapus!")
            else:
                print("Barang tidak ditemukan!")
            break
        else:
            print("Pilihan tidak valid! Ketikkan angka 1 untuk menghapus barang menggunakan kode barang atau angka 2 untuk mencari barang menggunakan nama barang")

def tampilkan_barang(inventory):
    print("Daftar Barang:")
    for barang in inventory.values():
        print(f"Kode: {barang['kode']}, Nama Barang: {barang['nama']}, Jumlah: {barang['jumlah']} buah, Harga: Rp{barang['harga']}")

def cari_barang(inventory):
    while True:
        cari = input("Cari menggunakan kode barang (1) atau menggunakan nama barang (2): ")
        if cari == "1":
            cari_kode_barang = input("Masukkan kode barang yang ingin dicari: ")
            if cari_kode_barang in inventory:
                barang = inventory[cari_kode_barang]
                print(f"Barang ditemukan: {barang['kode']}, {barang['nama']}, {barang['jumlah']} buah, Rp{barang['harga']}")
            else:
                print("Barang tidak ditemukan!")
            break
        elif cari == "2":
            cari_nama_barang = input("Masukkan nama barang yang ingin dicari: ").lower()
            hasil_pencarian = []
            for barang in inventory.values():
                if barang['nama'].lower() == cari_nama_barang:
                    hasil_pencarian.append(barang)
                if hasil_pencarian:
                    print("Hasil pencarian:")
                    for barang in hasil_pencarian:
                        print(f"Kode: {barang['kode']}, Nama Barang: {barang['nama']}, Jumlah: {barang['jumlah']} buah, Harga: Rp{barang['harga']}")
                else:
                    print("Barang tidak ditemukan!")
            break
        else:
            print("Pilihan tidak valid! Ketikkan angka 1 untuk mencari barang menggunakan kode barang atau angka 2 untuk mencari barang menggunakan nama barang")

def update_barang(inventory):
    while True:
        cari = input("Cari menggunakan kode barang (1) atau menggunakan nama barang (2): ")
        if cari == "1":
            kode_barang = input("Masukkan kode barang yang ingin diupdate: ")
            if kode_barang in inventory:
              try:
                jumlah_baru = int(input("Masukkan jumlah baru: "))
                if jumlah_baru < 1:
                  print("error karna bilangan negatif")
                  return

                harga_baru = int(input("Masukkan harga baru: "))
                if harga_baru < 1:
                  print("error karna bilangan negatif")
                  return
              except ValueError:
                print("error masukkan bialangan bulat")
                return


              inventory[kode_barang]['jumlah'] = jumlah_baru
              inventory[kode_barang]['harga'] = harga_baru
              print("Data barang berhasil diupdate!")
              return
            else:
                print("Kode barang tidak ditemukan!")
        elif cari == "2":
            nama_barang = input("Masukkan nama barang yang ingin diupdate: ").strip().lower()
            for barang, data in inventory.items():
                if data['nama'].lower() == nama_barang:
                    jumlah_baru = int(input("Masukkan jumlah baru: "))
                    if jumlah_baru<1:
                      print("error")
                      return
                    harga_baru = int(input("Masukkan harga baru: "))
                    if harga_baru<1:
                      print("error")
                      return
                    data['jumlah'] = jumlah_baru
                    data['harga'] = harga_baru
                    print("Data barang berhasil diupdate!")
                    return
            print(f"Barang dengan nama '{nama_barang}' tidak ditemukan.")
        else:
            print("Pilihan tidak valid! Ketikkan angka 1 untuk mencari barang menggunakan kode barang atau angka 2 untuk mencari barang menggunakan nama barang.")

inventory = {}

while True:
    print("\nMenu:")
    print("1. Tambah Barang")
    print("2. Hapus Barang")
    print("3. Tampilkan Daftar Barang")
    print("4. Cari Barang")
    print("5. Update Data Barang")
    print("6. Keluar")

    pilihan = input("Pilih menu: ")

    if pilihan == '1':
        tambah_barang(inventory)
    elif pilihan == '2':
        hapus_barang(inventory)
    elif pilihan == '3':
        tampilkan_barang(inventory)
    elif pilihan == '4':
        cari_barang(inventory)
    elif pilihan == '5':
        print(inventory)
        update_barang(inventory)
    elif pilihan == '6':
        print("Terima kasih telah menggunakan program inventory!")
        break
    else:
        print("Pilihan tidak valid!")

        #jika input atau update barang dengan jumlah dan harga yang nilainya dibawah 1 atau string akan muncul pesan error menggunakan try excepet atau if else