# -*- coding: utf-8 -*-
"""TUGASPRAKTIKUM_3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15AY60KMFSoFWOHRmCoqt0t9fgoM4k-OF

NAMA : MUHAMMAD DAFFA USMAN

NIM  :  H071241014

SOAL 1
"""

lebar_belah_ketupat = int(input('Masukkan Jumlah Baris: '))
print()

for i in range(lebar_belah_ketupat):
  if i%2 == 1:
    continue
  else:
    print(' ' * (lebar_belah_ketupat - i) + '* ' * (i + 1))

if lebar_belah_ketupat%2 == 1:
    for i in range(lebar_belah_ketupat):
        if i%2 == 0:
            continue
        else:
            print(' ' * (i + 2) + '* ' * (lebar_belah_ketupat - i - 1))
else:
    for i in range(lebar_belah_ketupat):
        if i%2 == 0:
            continue
        else:
            print(' ' * (i + 1) + '* ' * (lebar_belah_ketupat - i))

"""SOAL 2"""

import random
angka = random.randint(1, 100)
makscoba = 5
for i in range(makscoba):
    tebak = int(input("Masukkan tebakan Anda (ketik 0 untuk berhenti): "))
    if tebak == 0:
        print(f"angka rahasianya adalah {angka}")
        break
    if tebak < angka:
        print("Angka terlalu kecil")
    elif tebak > angka:
        print("Angka terlalu besar")
    else:
        print(f"Selamat! Anda menebak angka dengan benar. Angka rahasianya adalah {angka}")
if i == makscoba-1:
    print(f"Anda kehabisan percobaan. Angka rahasianya adalah {angka}")

"""SOAL 3"""

kode_N = int(input("N = "))
kode_M = int(input("M = "))

arah = 1

for i in range(kode_N):
    if i % 2 == 1:
        arah = -1
    else:
        arah = 1

    for j in range(kode_M):
        x = i
        y = j if arah == 1 else kode_M - j - 1
        print(f"MOVE to ({x}, {y})")

"""SOAL 4"""

total_harga = int(input("Masukkan total harga: "))
uang_tunai = int(input("Masukkan jumlah yang diberikan: "))

kembalian = uang_tunai - total_harga

if kembalian < 0:
    print("Uang yang diberikan kurang Rp", total_harga - uang_tunai )
elif kembalian == 0:
    print("Uang yang diberikan pas. Tidak ada kembalian.")

pecahan = [100000, 50000, 20000, 10000, 5000, 2000, 1000]
for nilai in pecahan:
    jumlah_pecahan = kembalian//nilai
    if jumlah_pecahan > 0:
        print(jumlah_pecahan, "lembar Rp", nilai)
        kembalian %= nilai

"""SOAL 5"""

populasi_A = int(input("Masukkan populasi awal Serangga A: "))
populasi_B = int(input("Masukkan populasi awal Serangga B: "))
jumlah_hari = int(input("Masukkan jumlah hari: "))

for hari in range(1, jumlah_hari + 1):
    if hari % 2 == 1:
      populasi_A = int(populasi_A + (populasi_A * 30/100))
      populasi_B = int(populasi_B + (populasi_B * 50/100))
    else:
      populasi_A = int(populasi_A - (populasi_A * 20/100))
      populasi_B = int(populasi_B - (populasi_B * 40/100))

    if hari % 5 == 0:
      populasi_A = int(populasi_A - (populasi_A * 10/100))
      populasi_B = int(populasi_B - (populasi_B * 10/100))
      print(f"Hari {hari}: Predator memakan 10% populasi.")
    print(f"Hari {hari}: Serangga A = {populasi_A}, Serangga B = {populasi_B}")