# -*- coding: utf-8 -*-
"""TUGASPRAKTIKUM_4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hR4DRViYK7rbdR205Fr350rM5AJG-hCV

NAMA : MUHAMMAD DAFFA USMAN

NIM : H071241014

SOAL 1
"""

import random
def kartu():
  return random.randint(1, 11)
def hitung_total(totalkartu):
  return sum(totalkartu)
def blackjack():
  print("Welcome to Blackjack!")
  kartu_player = [kartu()]
  kartu_dealer = [kartu()]

  while True:
    player_total = hitung_total(kartu_player)
    # print(f"Total kartu Anda sekarang adalah: {player_total}")
    choice = input("Apakah masih akan mengambil kartu? (y/n) ")
    if player_total > 21:
      print("Anda kalah! Kartu anda melebihi 21")
      print(f"Total kartu Anda sekarang adalah: {player_total}")
      return

    if choice.lower() == 'y':
      print(f"Total kartu Anda sekarang adalah: {player_total}")
      kartu_player.append(kartu())
    elif choice.lower() == 'n':
      break
    else:
      print('Inputan tidak valid')


  print(f"Kartu dealer adalah: {kartu_dealer[0]}")

  while hitung_total(kartu_dealer) < 17:
    kartu_dealer.append(kartu())
    print(f"Kartu dealer sekarang adalah: {hitung_total(kartu_dealer)}")

  player_total = hitung_total(kartu_player)
  dealer_total = hitung_total(kartu_dealer)

  if dealer_total > 21 and player_total < 22:
    print("Anda menang! Kartu dealer melebihi 21")
  elif player_total > dealer_total:
    print("Anda menang!")
  elif player_total < dealer_total:
    print("Dealer menang!")
  else:
    print("Seri!")

blackjack()
#jika kartu player > 21:otomatis kalah
#atasi jika input bukan y/n

"""SOAL 2"""

def cek_bahaya(jarak):
  return jarak > 20
def cari_harta_karun():
  total_jarak = 0
  ada_bahaya = False
  while True:
    try:
      langkah = int(input("Masukkan langkah (meter) atau 0 untuk selesai: "))
      if langkah == 0:
        break
      elif langkah < 0:
        print("Input tidak valid. Masukkan bilangan bulat positif.")
        continue
      total_jarak += langkah
      if cek_bahaya(langkah):
        ada_bahaya = True
    except ValueError:
      print("Input tidak valid. Masukkan bilangan bulat.")
      continue
  if ada_bahaya:
    print(f"Total jarak: {total_jarak} meter")
    print("Ada bahaya: Ya")
    print("Tidak aman untuk menggali harta karun. Coba lagi!")
  elif total_jarak == 50:
    print(f"Total jarak: {total_jarak} meter")
    print("Ada bahaya: Tidak")
    print("Aman! Kamu tepat menemukan harta karun dan menang!")
  else:
    print(f"Total jarak: {total_jarak} meter")
    print("Tidak menemukan harta karun. Coba lagi!")
cari_harta_karun()

"""SOAL 3"""

def hitung_langkah(n):

    langkah = 0
    while n != 1:
        if n <= 0:
            return -1
        elif n % 2 == 0:
            n //= 2
        else:
            n = 3 * n + 1
        print(n)
        langkah += 1
    return langkah

try:
    n = int(input("Masukkan angka: "))
    jumlah_langkah = hitung_langkah(n)
    if jumlah_langkah == -1:
        print("Input tidak valid (harus bilangan bulat positif)")
    else:
        print("Jumlah langkah:", jumlah_langkah)
except ValueError:
    print("Input tidak valid (harus bilangan bulat)")

"""SOAL 4"""

def kalkulator_sederhana():
    """Fungsi untuk melakukan perhitungan sederhana."""

    while True:
        try:
            angka1 = float(input("Masukkan angka pertama: "))
            angka2 = float(input("Masukkan angka kedua: "))
            operator = input("Masukkan operasi (+, -, *, /): ")

            if operator == "+":
                hasil = angka1 + angka2
            elif operator == "-":
                hasil = angka1 - angka2
            elif operator == "*":
                hasil = angka1 * angka2
            elif operator == "/":
                while angka2 == 0:
                    print("Pembagian dengan nol tidak diperbolehkan. Masukkan angka kedua yang berbeda:")
                    angka2 = float(input("Masukkan angka kedua: "))
                hasil = angka1 / angka2
            else:
                print("Operasi tidak valid. Gunakan +, -, *, atau /.")
                continue

            print("Hasil:", hasil)
            break

        except ValueError as e:
            print(f"Input tidak valid: {e}")

kalkulator_sederhana()