# -*- coding: utf-8 -*-
"""TUGASPRAKTIKUM_5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yUA1LmK16T0Sar0FQ2Jr73aDcb9QmC_J

SOAL 1
"""

def palindrome(string):

    string == string.lower().replace(" ","")
    return string == string[::-1]

frasa = input("palindrome: ")
string = frasa.lower()
if palindrome(string):
     print("Palindrome")
else:
    print("Not Palindrome")

"""SOAL 2"""

def akronim(string):

  teks = string.split()
  akronim = ""
  for kata in teks:
    akronim += kata[0].upper()
  return akronim

string = input("Masukkan string: ")
print(akronim(string))

"""SOAL 3"""

def hapus(str1, str2):

    freq1 = {}
    for char in str1:
        if char in freq1:
            freq1[char] += 1
        else:
            freq1[char] = 1

    penghapusan = 0
    for char in freq1:
        if char in str2:
            penghapusan += max(0, freq1[char] - str2.count(char))
        else:
            penghapusan += freq1[char]

    return penghapusan

str1 = input("Masukkan string pertama: ")
str2 = input("Masukkan string kedua: ")
print(f"Jumlah minimum penghapusan untuk membuat anagram: {hapus(str1, str2)}")

"""SOAL 4"""

def substring(string):

    substrings = []
    for i in range(len(string)):
        for j in range(i + 1, len(string) + 1):
            substrings.append(string[i:j])
    return substrings

string = input("Masukkan string: ")
all_substrings = substring(string)

for length in range(1, len(string) + 1):
    for i in range(len(string) - length + 1):
        print(string[i:i+length])

"""SOAL 5"""

def kriptografi(text, shift):

  alphabet = "abcdefghijklmnopqrstuvwxyz"
  result = ""
  for char in text:
    if char.lower() in alphabet:
      index = alphabet.find(char.lower())
      new_index = (index + shift) % len(alphabet)
      new_char = alphabet[new_index]
      new_char = new_char.upper() if char.isupper() else new_char
      result += new_char
    else:
      result += char
  return result

text = input("Masukkan String: ")
shift = int(input("Masukkan jumlah pergeseran: "))

cipher_text = kriptografi(text, shift)
print(f"Text: {text}")
print(f"Shift: {shift}")
print(f"Cipher: {cipher_text}")