# -*- coding: utf-8 -*-
"""TUGASPRAKTIKUM_8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/161LOzCmCsL4NsMzWHGERGObDWmdQfaAX

SOAL 1
"""

import re

pattern = r'^[A-Za-z02468]{40}[13579\s]{5}$'
string = input("Masukkan string: ")
result = re.match(pattern, string)


if result:
    print("True")
else:
    print("False")
    print("String tersebut memiliki panjang tepat 45 karakter.")
    print("40 karakter pertama harus terdiri dari huruf uppercase atau lowercase atau digit bernilai genap.")
    print("5 karakter terakhir terdiri dari digit bernilai ganjil atau whitespace character.")

for i in range(45):
  print(2,end="")

"""SOAL 2"""

import re

ipv4_pattern = r"^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$"
ipv6_pattern = r"^[0-9a-fA-F]{1,4}(:[0-9a-fA-F]{1,4}){7}$"

N = int(input("jumlah baris: "))
addresses = []
for _ in range(N):
    address = input().strip()
    addresses.append(address)

results = []
for address in addresses:
    if re.match(ipv4_pattern, address):
        octets = address.split('.')
        if all(0 <= int(octet) <= 255 for octet in octets):
            results.append("IPv4")
        else:
            results.append("Bukan IP Address")
    elif re.match(ipv6_pattern, address):
        results.append("IPv6")
    else:
        results.append("Bukan IP Address")

print(*results, sep='\n')

"""SOAL 3"""

import re

def is_valid_username(username):
    pattern = r"^[a-zA-Z0-9]{5,20}$"
    return re.search(pattern, username)

def is_valid_email(email):
    pattern = r"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.(com|co\.id)$"
    return re.search(pattern, email)

def is_valid_password(password):
    pattern = r"^(?=.[a-z])(?=.[A-Z])(?=.*\d)[a-zA-Z\d]{8,}$"
    return re.search(pattern, password)

while True:
    username = input("Masukkan username: ")
    if is_valid_username(username):
        email = input("Masukkan email: ")
        if is_valid_email(email):
            password = input("Masukkan password: ")
            if is_valid_password(password):
                print(f"\nRegistrasi berhasil! Selamat datang, {username}!")
                break
            else:
                print("\nPassword yang kamu input beresiko dihack. Registrasi gagal.")
        else:
            print("\nEmail yang kamu input tidak valid. Registrasi gagal!")
    else:
      print("\nInputan username tidak valid dalam sistem. Registrasi gagal!")